#!/bin/bash
set -e
CONFIG=${1-"/usr/share/self-service-password/conf/config.inc.php"}
echo "Changing self-service-password config $CONFIG"

replace () {
  echo "setting $1 to $2" 
  sed -i "/^$1 = /s/= .*;/= $2;/g" $CONFIG

}

replace_string () {
  echo "setting $1 to $2" 
  sed -i "/^$1 = /s/= .*;/= \"$2\";/g" $CONFIG

}

if [ -n "$LDAP_URL" ]; then
  replace_string '$ldap_url' $LDAP_URL
fi

if [ -n "$LDAP_STARTTLS" ]; then
  replace '$ldap_starttls' $LDAP_STARTTLS
fi

if [ -n "$LDAP_BINDDN" ]; then
  replace_string '$ldap_binddn' $LDAP_BINDDN
fi

if [ -n "$LDAP_BINDPW" ]; then
  replace_string '$ldap_bindpw' $LDAP_BINDPW
fi

if [ -n "$LDAP_BASE" ]; then
  replace_string '$ldap_base' $LDAP_BASE
fi

if [ -n "$LDAP_LOGIN_ATTR" ]; then
  replace_string '$ldap_login_attribute' $LDAP_LOGIN_ATTR
fi

if [ -n "$LDAP_FULLNAME_ATTR" ]; then
  replace_string '$ldap_fullname_attribute' $LDAP_FULLNAME_ATTR
fi

if [ -n "$LDAP_FILTER" ]; then
  replace_string '$ldap_filter' $LDAP_FILTER
fi

if [ -n "$AD_MODE" ]; then
  replace '$ad_mode' $AD_MODE
fi

if [ -n "$HASH" ]; then
  replace_string '$hash' $HASH
fi

if [ -n "$USE_QUESTIONS" ]; then
  replace '$use_questions' $USE_QUESTIONS
fi

if [ -n "$ANSWER_OBJECT_CLASS" ]; then
  replace_string '$answer_objectClass' $ANSWER_OBJECT_CLASS
fi

if [ -n "$ANSWER_ATTR" ]; then
  replace_string '$answer_attribute' $ANSWER_ATTR
fi

if [ -n "$USE_TOKENS" ]; then
  replace '$use_tokens' $USE_TOKENS
fi

if [ -n "$CRYPT_TOKENS" ]; then
  replace '$crypt_tokens' $CRYPT_TOKENS
fi

if [ -n "$TOKEN_LIFETIME" ]; then
  replace_string '$token_lifetime' $TOKEN_LIFETIME
fi

if [ -n "$MAIL_ATTRIBUTE" ]; then
  replace_string '$mail_attribute' $MAIL_ATTRIBUTE
fi

